version: "3"
services:
  sync-mysql:
    container_name: syncdbs
    restart: always
    # either build yourself or use the image from docker hub
    build: .
    #image: ballavamsi/syncdbs-mysql:latest
    environment:
      DBS_FILE: /data/dbs.yaml
      BACKUP_DIR: /data/backups
      RUN_ON_STARTUP: "1"
    volumes:
      - ./data:/data
    networks:
      vamsi-docker-net:

networks:
  vamsi-docker-net:
    external: true